### DISCUSSION TITLE
/validator/add/ - endpoint

### DISCUSSION THREAD

**Discussion by lalalaurentiu** [lalalaurentiu/scraper_Api#1] [Q&A]
# Strategia de Testare API Endpoint [/validator/add](https://api.laurentiumarian.ro/validator/add/)

## Scop
Strategia de testare are ca scop evaluarea corectitudinii și stabilității API-ului api.laurentiumarian.ro, în special pentru endpoint-ul /validator/add.

## Pregătire
1. Asigură-te că ai acces la specificațiile API-ului și că înțelegi detaliile funcționale și tehnice.
2. Obține un token de autentificare valid pentru utilizare în teste.

### Pas 1: Obținerea Token-ului prin Redirecționare către GitHub pentru Autentificare

**1.1 Descriere:**
- După accesarea url-ului [homepage](https://api.laurentiumarian.ro/homepage/) serverul va redirecționa utilizatorul către pagina de autentificare GitHub. Dacă autentificarea este cu succes, serverul va furniza un token valid.

**1.2 Cerere HTTP:**
- Metoda: GET
    - URL: `api.laurentiumarian.ro/homepage/`

**1.3 Răspuns Așteptat:**
- Redirecționarea către pagina de autentificare GitHub. După autentificare cu succes, redirecționare către `127.0.0.1:5500/profile/index.html?Token=<token_valid>`.

**1.4 Exemplu:**
- Cerere:
  - GET `api.laurentiumarian.ro/homepage/`
- Redirecționare către pagina de autentificare GitHub.
- După autentificare cu succes, redirecționare către `127.0.0.1:5500/profile/index.html?Token=<token_valid>`.

Asigură-te că token-ul obținut în acest mod este utilizat în mod corespunzător în cererile ulterioare către endpoint-ul de validare.

### Pas 2: Efectuarea unei Cereri POST către Endpoint-ul de Validare

**2.1 Descriere:**
- După obținerea token-ului valid prin redirecționare de la `/homepage/`, efectuează o cerere POST către `/validator/add`. Corpul cererii trebuie să conțină un obiect valid conform specificațiilor.

**2.2 Cerere HTTP:**
- Metoda: POST
    - URL: `api.laurentiumarian.ro/validator/add`
- Antete:
  - Content-Type: application/json
  - Authorization: Token <token_obținut>
- Corpul Cererii:

```json
[
    {
      "job_title": ["Procurer with German"],
      "job_link": ["https://michelinhr.wd3.myworkdayjobs.com/en-US/Michelin/job/Voluntari/Procurer-with-German_R-2023039242"],
      "country": ["România"],
      "city": ["Voluntari"],
      "county": ["Ilfov"],
      "company": ["Michelin"]
    }
]
```

**2.3 Răspuns Așteptat:**
- Verifică că răspunsul are un cod de stare 200 sau 201, indicând succesul validării. Body:

```yaml
[
    {
        "job_link": "https://michelinhr.wd3.myworkdayjobs.com/en-US/Michelin/job/Voluntari/Procurer-with-German_R-2023039242",
        "job_title": "Procurer with German",
        "company": 2, # id-ul companiei
        "country": "România",
        "city": "Voluntari",
        "county": "Ilfov",
        "remote": "",
        "job_id": "b954ea481832db0900585617a9ea14db", # id-ul jobului
        "company_name": "michelin" # numele companiei
    }
]
```

**2.4 Exemplu:**
Cerere:
- Metodă: POST
- URL: `api.laurentiumarian.ro/validator/add`
- Antete:
  - Content-Type: application/json
  - Authorization: Token <token_obținut>
- Corpul Cererii:

```json
[
    {
      "job_title": ["Procurer with German"],
      "job_link": ["https://michelinhr.wd3.myworkdayjobs.com/en-US/Michelin/job/Voluntari/Procurer-with-German_R-2023039242"],
      "country": ["România"],
      "city": ["Voluntari"],
      "county": ["Ilfov"],
      "company": ["Michelin"]
    }
]
```

Răspuns:

- Status: 200 OK
- Body:
```yaml
[
    {
        "job_link": "https://michelinhr.wd3.myworkdayjobs.com/en-US/Michelin/job/Voluntari/Procurer-with-German_R-2023039242",
        "job_title": "Procurer with German",
        "company": 2, # id-ul companiei
        "country": "România",
        "city": "Voluntari",
        "county": "Ilfov",
        "remote": "",
        "job_id": "b954ea481832db0900585617a9ea14db", # id-ul jobului
        "company_name": "michelin" # numele companiei
    }
]
```

### Pas 3: Test de Eșec - Autentificare Eșuată: Răspuns Așteptat:

Verifică că răspunsul include un cod de stare 401 sau 403, indicând o autentificare eșuată. Conținutul răspunsului ar trebui să conțină un mesaj de eroare relevant.

**Exemplu:**
- **Cerere:**
  - Metodă: POST
  - URL: `api.laurentiumarian.ro/validator/add`
  - Antete:
    - Content-Type: application/json
    - Authorization: Token <token_invalid>
  - Corpul Cererii:
    ```json
    [
        {
          "job_title": ["Procurer with German"],
          "job_link": ["https://michelinhr.wd3.myworkdayjobs.com/en-US/Michelin/job/Voluntari/Procurer-with-German_R-2023039242"],
          "country": ["România"],
          "city": ["Voluntari"],
          "county": ["Ilfov"],
          "company": ["Michelin"]
        }
    ]
    ```
- **Răspuns:**
  - Status: 401 Unauthorized
  - Body:
    ```json
    {
        {"detail":"Invalid token."}
    }
    ```

Acest exemplu arată cum API-ul ar trebui să gestioneze o autentificare eșuată și să returneze un cod de stare 401, împreună cu un mesaj de eroare specific.

### Pas 4: Test de Performanță: Răspuns Așteptat:

Verifică că răspunsul are un cod de stare 200 sau 201 pentru fiecare cerere, indicând succesul validării. Verifică timpul de răspuns pentru fiecare cerere, asigurându-te că sistemul se comportă în mod eficient în condiții de solicitare crescută.

**Exemplu:**
1. Realizează un număr semnificativ de cereri POST către `api.laurentiumarian.ro/validator/add/` într-un interval scurt de timp.
2. Monitorizează codurile de stare și timpii de răspuns pentru a identifica eventuale probleme de performanță.

**Observații:**
- Un număr mare de cereri ar trebui să fie tratat eficient, cu timpi de răspuns rezonabili.
- În timpul testelor de performanță, verifică dacă sistemul rămâne stabil și dacă nu apar erori sau întârzieri semnificative.
